name: rest_api
description: "Nexus Beery Assignment RestAPIs GetX Flutter project."

publish_to: 'www.qrdpro.com/app/nexus/restapi'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  http: ^1.3.0
  get: ^4.7.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^5.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/brands/
    - assets/flags/
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
